name: Audit JavaScript

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - dev
    paths:
      - '.github/workflows/audit-javascript.yml'
      - "**/pnpm-lock.yaml"
      - "**/package.json"
  pull_request:
    branches:
      - dev
    paths:
      - '.github/workflows/audit-javascript.yml'
      - "**/pnpm-lock.yaml"
      - "**/package.json"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  audit-javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: pnpm/action-setup@v2.2.2
        with:
          run_install: true
      - name: audit
        run: pnpm audit